# Welcome to the Feature Engineering Notebook II

<div class="alert alert-block alert-warning">
Click on the interactive table of contents to look deeper into the code for a feature
</div>

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Loading-the-data" data-toc-modified-id="Loading-the-data-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Loading the data</a></span></li><li><span><a href="#Reaction-Time" data-toc-modified-id="Reaction-Time-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Reaction Time</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#mean_reaction_time" data-toc-modified-id="mean_reaction_time-2.0.1"><span class="toc-item-num">2.0.1&nbsp;&nbsp;</span><code>mean_reaction_time</code></a></span></li><li><span><a href="#median_reaction_time" data-toc-modified-id="median_reaction_time-2.0.2"><span class="toc-item-num">2.0.2&nbsp;&nbsp;</span><code>median_reaction_time</code></a></span></li><li><span><a href="#var_reaction_time" data-toc-modified-id="var_reaction_time-2.0.3"><span class="toc-item-num">2.0.3&nbsp;&nbsp;</span><code>var_reaction_time</code></a></span></li></ul></li><li><span><a href="#reaction_time_df" data-toc-modified-id="reaction_time_df-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>reaction_time_df</a></span></li></ul></li><li><span><a href="#Bid-counts" data-toc-modified-id="Bid-counts-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Bid counts</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#total_bids" data-toc-modified-id="total_bids-3.0.1"><span class="toc-item-num">3.0.1&nbsp;&nbsp;</span><code>total_bids</code></a></span></li><li><span><a href="#mean_bids_per_day" data-toc-modified-id="mean_bids_per_day-3.0.2"><span class="toc-item-num">3.0.2&nbsp;&nbsp;</span><code>mean_bids_per_day</code></a></span></li><li><span><a href="#relating-to-bids-per-auction" data-toc-modified-id="relating-to-bids-per-auction-3.0.3"><span class="toc-item-num">3.0.3&nbsp;&nbsp;</span>relating to bids per auction</a></span><ul class="toc-item"><li><span><a href="#mean_bids_per_auction" data-toc-modified-id="mean_bids_per_auction-3.0.3.1"><span class="toc-item-num">3.0.3.1&nbsp;&nbsp;</span><code>mean_bids_per_auction</code></a></span></li><li><span><a href="#median_bids_per_auction" data-toc-modified-id="median_bids_per_auction-3.0.3.2"><span class="toc-item-num">3.0.3.2&nbsp;&nbsp;</span><code>median_bids_per_auction</code></a></span></li></ul></li></ul></li><li><span><a href="#bids_counts_df" data-toc-modified-id="bids_counts_df-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>bids_counts_df</a></span></li></ul></li><li><span><a href="#Bidding-Activity" data-toc-modified-id="Bidding-Activity-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Bidding Activity</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#mean_time_variance_per_day" data-toc-modified-id="mean_time_variance_per_day-4.0.1"><span class="toc-item-num">4.0.1&nbsp;&nbsp;</span><code>mean_time_variance_per_day</code></a></span></li><li><span><a href="#first_thirtymins_df" data-toc-modified-id="first_thirtymins_df-4.0.2"><span class="toc-item-num">4.0.2&nbsp;&nbsp;</span><code>first_thirtymins_df</code></a></span></li><li><span><a href="#second_thirtymins_df" data-toc-modified-id="second_thirtymins_df-4.0.3"><span class="toc-item-num">4.0.3&nbsp;&nbsp;</span><code>second_thirtymins_df</code></a></span></li><li><span><a href="#last_thirtymins_df" data-toc-modified-id="last_thirtymins_df-4.0.4"><span class="toc-item-num">4.0.4&nbsp;&nbsp;</span><code>last_thirtymins_df</code></a></span></li><li><span><a href="#secondlast_thirtymins_df" data-toc-modified-id="secondlast_thirtymins_df-4.0.5"><span class="toc-item-num">4.0.5&nbsp;&nbsp;</span><code>secondlast_thirtymins_df</code></a></span></li><li><span><a href="#meanbids_in_20mins_df" data-toc-modified-id="meanbids_in_20mins_df-4.0.6"><span class="toc-item-num">4.0.6&nbsp;&nbsp;</span><code>meanbids_in_20mins_df</code></a></span></li></ul></li><li><span><a href="#bidding_activity_df" data-toc-modified-id="bidding_activity_df-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>bidding_activity_df</a></span></li></ul></li><li><span><a href="#Bidder-Downtime" data-toc-modified-id="Bidder-Downtime-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Bidder Downtime</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#mean_downtime_df" data-toc-modified-id="mean_downtime_df-5.0.1"><span class="toc-item-num">5.0.1&nbsp;&nbsp;</span><code>mean_downtime_df</code></a></span></li><li><span><a href="#median_downtime_df" data-toc-modified-id="median_downtime_df-5.0.2"><span class="toc-item-num">5.0.2&nbsp;&nbsp;</span><code>median_downtime_df</code></a></span></li><li><span><a href="#var_downtime_df" data-toc-modified-id="var_downtime_df-5.0.3"><span class="toc-item-num">5.0.3&nbsp;&nbsp;</span><code>var_downtime_df</code></a></span></li></ul></li><li><span><a href="#bidder_downtime_df" data-toc-modified-id="bidder_downtime_df-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>bidder_downtime_df</a></span></li></ul></li><li><span><a href="#Others" data-toc-modified-id="Others-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Others</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#mean_time_between_diff_ips" data-toc-modified-id="mean_time_between_diff_ips-6.0.1"><span class="toc-item-num">6.0.1&nbsp;&nbsp;</span><code>mean_time_between_diff_ips</code></a></span></li></ul></li></ul></li><li><span><a href="#Old-and-unclassified-features" data-toc-modified-id="Old-and-unclassified-features-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Old and unclassified features</a></span><ul class="toc-item"><li><span><a href="#bids_per_url_df" data-toc-modified-id="bids_per_url_df-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>bids_per_url_df</a></span></li><li><span><a href="#bids_per_ip_df" data-toc-modified-id="bids_per_ip_df-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>bids_per_ip_df</a></span></li><li><span><a href="#sets_df" data-toc-modified-id="sets_df-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>sets_df</a></span></li><li><span><a href="#bids_per_country_df" data-toc-modified-id="bids_per_country_df-7.4"><span class="toc-item-num">7.4&nbsp;&nbsp;</span>bids_per_country_df</a></span></li><li><span><a href="#objects_df" data-toc-modified-id="objects_df-7.5"><span class="toc-item-num">7.5&nbsp;&nbsp;</span>objects_df</a></span></li></ul></li><li><span><a href="#Inspiried-by-fakeplastictress" data-toc-modified-id="Inspiried-by-fakeplastictress-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Inspiried by fakeplastictress</a></span><ul class="toc-item"><li><span><a href="#auction_bid_count_df" data-toc-modified-id="auction_bid_count_df-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>auction_bid_count_df</a></span></li></ul></li><li><span><a href="#Combining-all-features!" data-toc-modified-id="Combining-all-features!-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Combining all features!</a></span><ul class="toc-item"><li><span><a href="#Fill-in-missing-values" data-toc-modified-id="Fill-in-missing-values-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Fill in missing values</a></span></li><li><span><a href="#Add-on-features" data-toc-modified-id="Add-on-features-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Add on features</a></span></li><li><span><a href="#Save-to-CSV-file" data-toc-modified-id="Save-to-CSV-file-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>Save to CSV file</a></span></li></ul></li></ul></div>

---

## Loading the data

Import required packages:

In [29]:
import pandas as pd
import numpy as np

pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

Read `bids.csv` into a dataframe:

In [3]:
bids_df = pd.read_csv('data/bids.csv')

Split data into 9 days:

- **Total time (a.u.):** 140968000000000.0  
- **Assumption:** There are a total of 31 days worth of bids in the bids_df.  
- **Time (a.u.) per day:** 4547354838709.678.  
- **One hour:** 189473118279.56992 a.u.  
- **One minute:** 3157885304.6594987 a.u.  
- **One second:** 3157885304.6594987 a.u.  
  
|Set|Day|Start|End (inclusive)| 
|:---:|:---:|:---|:---|
|1|1|9631916842105263|9636464196943974.0|	
|1|2|9636464196943974.0|9641011551782684.0|	
|1|3|9641011551782684.0|9645558906621394.0|	
|2|4|9695580000000000|9700127354838710.0|	
|2|5|9700127354838710.0|9704674709677420.0|
|2|6|9704674709677420.0|9709222064516130.0|
|3|7|9759243157894736|9763790512733446.0|
|3|8|9763790512733446.0|9768337867572156.0|
|3|9|9768337867572156.0|9772885222410866.0|

In [4]:
temp_df = bids_df[['bidder_id','time','auction']]   # most of the cell below only require these three columns. 
                                                    # will create a new df if other columns are needed

# set 1
day1 = temp_df.loc[temp_df.time <= 9636464196943974.0]
day2 = temp_df.loc[(temp_df.time > 9636464196943974.0) & (temp_df.time <= 9641011551782684.0)]
day3 = temp_df.loc[(temp_df.time > 9641011551782684.0) & (temp_df.time <= 9645558906621394.0)]

# set 2
day4 = temp_df.loc[(temp_df.time >= 9695580000000000) & (temp_df.time <= 9700127354838710.0)]
day5 = temp_df.loc[(temp_df.time > 9700127354838710.0) & (temp_df.time <= 9704674709677420.0)]
day6 = temp_df.loc[(temp_df.time > 9704674709677420.0) & (temp_df.time <= 9709222064516130.0)]

# set 3
day7 = temp_df.loc[(temp_df.time >= 9759243157894736) & (temp_df.time <= 9763790512733446.0)]
day8 = temp_df.loc[(temp_df.time > 9763790512733446.0) & (temp_df.time <= 9768337867572156.0)]
day9 = temp_df.loc[temp_df.time > 9768337867572156.0]

In [22]:
# reaction_time_df = pd.read_csv('reaction_time_df.csv')
# thirtymins_df = pd.read_csv('thirtymins.csv')
# bidder_downtime_df = pd.read_csv('time_between_bids.csv')

---

## Reaction Time

Reaction time is the time difference between two bidder's bids in the same auction on the same day.  
  
First retrieve the individual reaction time of each transaction record in `bids_df`.

In [42]:
# shortcut to obtain reaction_time_raw_df
reaction_time_raw_df = pd.read_csv('raw_data/reaction_time_raw.csv')

In [28]:
# create a starting dataframe
reaction_time_df = pd.DataFrame(columns=['bidder_id','time'])

# create list to iterate through
days = [day1,day2,day3,day4,day5,day6,day7,day8,day9]
current_day = 0 # to track output

for day in days:
    current_day += 1
    
    # get list of unique auction for the specific day
    unique_auctions = list(day.auction.unique())
    
    # iterate through the individual auctions
    for auction in unique_auctions:
        
        # get the transactions for that unique auction
        auction_df = day.loc[day.auction == auction].set_index('bidder_id').drop(columns='auction',axis=1)
        
        # get time diff
        auction_df = auction_df.diff()
        
        # reset index to append to reation_time_df
        auction_df = auction_df.reset_index()
        reaction_time_df = pd.concat([reaction_time_df, auction_df],ignore_index=True)
        
    # print(f'| Day {current_day} done |', end=' ') # to track output

| Day 1 done | | Day 2 done | | Day 3 done | | Day 4 done | | Day 5 done | | Day 6 done | | Day 7 done | | Day 8 done | | Day 9 done |

In [43]:
reaction_time_raw_df

                                     bidder_id          time
0        6b18a5b1eb756ed0968e726077ac6f574a163           NaN
1        c2010cc2ce0c23abdadc45ba40c83928e5fc3  5.736842e+09
2        c2010cc2ce0c23abdadc45ba40c83928e5fc3  3.684211e+08
3        c2010cc2ce0c23abdadc45ba40c83928e5fc3  4.736842e+08
4        c2010cc2ce0c23abdadc45ba40c83928e5fc3  9.473684e+08
...                                        ...           ...
7656329  d655a1e7dc5331df3606093770e9b70dc7e19           NaN
7656330  ac91542dc245b6fb01a2abb6e41bf16f1fb4e           NaN
7656331  d655a1e7dc5331df3606093770e9b70dc7e19           NaN
7656332  d655a1e7dc5331df3606093770e9b70dc7e19  1.631579e+09
7656333  d06c7e8e7d9f968db5c71d11b5c04cede65f1           NaN

[7656334 rows x 2 columns]

#### `mean_reaction_time`

In [44]:
mean_reaction_time_df = reaction_time_raw_df.groupby('bidder_id').mean().rename({'time':'mean_reaction_time'},axis=1)

#### `median_reaction_time`

In [45]:
median_reaction_time_df = reaction_time_raw_df.groupby('bidder_id').median().rename({'time':'median_reaction_time'},axis=1)

#### `var_reaction_time`

In [46]:
var_reaction_time_df = reaction_time_raw_df.groupby('bidder_id').var().rename({'time':'var_reaction_time'},axis=1)

### reaction_time_df

In [47]:
reaction_time_df = pd.concat([mean_reaction_time_df,median_reaction_time_df,var_reaction_time_df],axis=1)
reaction_time_df

,mean_reaction_time,median_reaction_time,var_reaction_time
bidder_id,,,
0013f9b8d1f462df4462e1c1216e441ba6e18,2.828947e+09,5.263158e+08,1.607736e+19
0014e3b911d1420e43ced1dc4fc18fde0fd0c,1.197744e+10,7.894737e+08,5.673286e+20
002828f800c5132e297cfe3d44fbde9aeac51,1.263158e+09,1.263158e+09,1.795014e+18
00402f50c4086f320cb6bf94f04462ea32441,3.189772e+10,1.526316e+09,2.478017e+22
0040cea6b93afd86768c365d89513ffb7c0ba,6.811754e+10,1.247368e+10,1.977747e+22
...,...,...,...
ffd49be672b1ba493b07dccf29311045c5392,1.574299e+11,8.078947e+10,3.878959e+22
ffdd8ed91a683b0f2a8237798ebe9214e3c43,1.106632e+11,9.473684e+10,1.204035e+22
ffde8717e9a547d536a4e9c3f44782829c021,1.230263e+09,3.947368e+08,2.836279e+18
ffe66dcb4b34bdbb5e17d7db7b1395e3fbbb7,1.019298e+10,1.026316e+10,3.989289e+19
ffef2a34068ab5328795bc9ed2da46aa29626,4.677057e+09,1.157895e+09,1.454074e+20

---

## Bid counts

#### `total_bids`
Total bid count per unique bidder

In [48]:
# groupby bidder and count number of bids
total_bids_df = bids_df.groupby('bidder_id').count().reset_index()

# keep bidder_id and another random column, rename the random column to feature name
total_bids_df = total_bids_df[['bidder_id','auction']].rename({'auction':'total_bids'},axis=1).set_index('bidder_id')

#### `mean_bids_per_day`

In [49]:
# create empty df
bids_per_day_df = pd.DataFrame(columns=['bidder_id','time'])

# create list of data split into 9 days, to iterate through
days = [day1,day2,day3,day4,day5,day6,day7,day8,day9]

for day in days:
    
    # drop 'auction' as it is not needed
    day = day.drop(columns=['auction'],axis=1)
    
    # count number of bids each unique bidder made
    day_df = day.groupby('bidder_id').count().reset_index()
    
    # add bids counts to the dataframe created above
    bids_per_day_df = pd.concat([bids_per_day_df,day_df],ignore_index=True)

# convert time from object to int
bids_per_day_df['time'] = bids_per_day_df['time'].apply(int)

# get the mean bids per day
mean_bids_per_day_df = bids_per_day_df.groupby('bidder_id').mean()
mean_bids_per_day_df = mean_bids_per_day_df.rename({'time':'mean_bids_per_day'},axis=1)

#### relating to bids per auction

In [50]:
# shortcut to get bids_per_auction_df
bids_per_auction_df = pd.read_csv('raw_data/bids_per_auction.csv')

In [ ]:
days = [day1,day2,day3,day4,day5,day6,day7,day8,day9]

# get unique auctions for each of the 9 days
unique_auctions = []
for day in days:
    unique_auctions.append(list(day.auction.unique()))

# create empty df
bids_per_auction_df = pd.DataFrame(columns=['bidder_id','auction'])

# iterate through the 9 days
for i in range(9):
    day = days[i].drop(columns='time',axis=1)
    unique_auctions_list = unique_auctions[i]
    for auction in unique_auctions_list:
        auction_df = day.loc[day.auction == auction]
        bid_count_df = auction_df.groupby('bidder_id').count().reset_index()
        bids_per_auction_df = pd.concat([bids_per_auction_df,bid_count_df],ignore_index=True)
        
# change values in auction column to int
bids_per_auction_df['auction'] = bids_per_auction_df['auction'].apply(int)

##### `mean_bids_per_auction`

In [51]:
mean_bids_per_auction_df = bids_per_auction_df.groupby('bidder_id').mean().rename({'auction':'mean_bids_per_auction'},axis=1)

##### `median_bids_per_auction`

In [52]:
median_bids_per_auction_df = bids_per_auction_df.groupby('bidder_id').median().rename({'auction':'median_bids_per_auction'},axis=1)

### bids_counts_df

In [53]:
bids_counts_df = pd.concat([mean_bids_per_auction_df,median_bids_per_auction_df,mean_bids_per_day_df,total_bids_df],axis=1)
bids_counts_df

,mean_bids_per_auction,median_bids_per_auction,mean_bids_per_day,total_bids
bidder_id,,,,
0013f9b8d1f462df4462e1c1216e441ba6e18,1.142857,1.0,2.666667,8
0014e3b911d1420e43ced1dc4fc18fde0fd0c,1.000000,1.0,2.333333,7
002828f800c5132e297cfe3d44fbde9aeac51,1.000000,1.0,1.000000,2
00402f50c4086f320cb6bf94f04462ea32441,2.057851,1.0,83.000000,249
0040cea6b93afd86768c365d89513ffb7c0ba,1.068966,1.0,5.166667,31
...,...,...,...,...
ffd49be672b1ba493b07dccf29311045c5392,5.600000,2.5,56.000000,168
ffdd8ed91a683b0f2a8237798ebe9214e3c43,1.000000,1.0,2.500000,5
ffde8717e9a547d536a4e9c3f44782829c021,1.142857,1.0,4.000000,24
ffe66dcb4b34bdbb5e17d7db7b1395e3fbbb7,1.000000,1.0,3.000000,3
ffef2a34068ab5328795bc9ed2da46aa29626,1.337662,1.0,51.500000,103

---

## Bidding Activity
mean_time_variance_per_day
 bids in first 30mins of a day
 bids in second 30mins of a day
 bid in last 30mins of a day
 bids in second last 30mins of a day
 Avg bids in 20mins

#### `mean_time_variance_per_day`

In [54]:
time_variance_per_day_df = pd.DataFrame(columns=['bidder_id','time'])

days = [day1,day2,day3,day4,day5,day6,day7,day8,day9]

for day in days:
    day_df = day.groupby('bidder_id').var().reset_index()
    time_variance_per_day_df = pd.concat([time_variance_per_day_df,day_df],ignore_index=True)

mean_time_variance_per_day_df = time_variance_per_day_df.groupby('bidder_id').mean()
mean_time_variance_per_day_df = mean_time_variance_per_day_df.rename({'time':'mean_time_variance_per_day'},axis=1)

#### `first_thirtymins_df`
- bids placed in the first 30mins of the day

In [55]:
one_min = 3157885304.6594987
thirty_mins = one_min*30

days = [day1,day2,day3,day4,day5,day6,day7,day8,day9]

# get start timings
one_day = 4547354838709.678
start = [9631916842105263, 9695580000000000, 9759243157894736]
start_times = []
for i in range(len(start)):
    for _ in range(3):
        start_times.append(start[i])
        start[i]+=one_day


first_thirtymins_df = pd.DataFrame(columns=['bidder_id','time'])

for i in range(9):
    day = days[i]
    day = day.drop(columns=['auction'],axis=1)
    thirtymins = day.loc[(day.time >= start_times[i]) & (day.time < (start_times[i]+thirty_mins))]
    first_thirtymins_df = pd.concat([first_thirtymins_df,thirtymins],ignore_index=True)
    #print(f'Day {i+1} done.') # to track output
    
first_thirtymins_df = first_thirtymins_df.groupby('bidder_id').count().rename({'time':'bids_in_firstthirty'},axis=1)

#### `second_thirtymins_df`
- bids placed in the second 30mins of the day

In [56]:
one_min = 3157885304.6594987
thirty_mins = one_min*30

days = [day1,day2,day3,day4,day5,day6,day7,day8,day9]

# get start timings
one_day = 4547354838709.678
start = [9631916842105263, 9695580000000000, 9759243157894736]
start_times = []
for i in range(len(start)):
    for _ in range(3):
        start_times.append(start[i])
        start[i]+=one_day

second_thirtymins_df = pd.DataFrame(columns=['bidder_id','time'])

for i in range(9):
    day = days[i]
    day = day.drop(columns=['auction'],axis=1)
    thirtymins = day.loc[(day.time >= start_times[i]+thirty_mins) & (day.time < (start_times[i]+thirty_mins*2))]
    second_thirtymins_df = pd.concat([second_thirtymins_df,thirtymins],ignore_index=True)
    #print(f'Day {i+1} done.')

second_thirtymins_df = second_thirtymins_df.groupby('bidder_id').count().rename({'time':'bids_in_secondthirty'},axis=1)

#### `last_thirtymins_df`
- bids placed in the last 30mins of the day

In [57]:
# bids placed in last 30mins of the day
days = [day1,day2,day3,day4,day5,day6,day7,day8,day9]
one_min = 3157885304.6594987
thirty_mins = one_min*30

# get end timings
one_day = 4547354838709.678
ends = [9631916842105263, 9695580000000000, 9759243157894736]
end_times = []
for i in range(len(ends)):
    for _ in range(3):
        end_times.append(ends[i]+one_day)
        ends[i]+=one_day

last_thirtymins_df = pd.DataFrame(columns=['bidder_id','time'])

for i in range(9):
    day = days[i]
    day = day.drop(columns=['auction'],axis=1)
    thirtymins = day.loc[(day.time > (end_times[i]-thirty_mins)) & (day.time <= end_times[i])]
    last_thirtymins_df = pd.concat([last_thirtymins_df,thirtymins],ignore_index=True)
    #print(f'Day {i+1} done.') # to track output
    
last_thirtymins_df = last_thirtymins_df.groupby('bidder_id').count().rename({'time':'bids_in_lastthirty'},axis=1)

#### `secondlast_thirtymins_df`
- bids placed in the second last 30mins of the day

In [58]:
one_min = 3157885304.6594987
thirty_mins = one_min*30

days = [day1,day2,day3,day4,day5,day6,day7,day8,day9]

# get end timings
one_day = 4547354838709.678
ends = [9631916842105263, 9695580000000000, 9759243157894736]
end_times = []
for i in range(len(ends)):
    for _ in range(3):
        end_times.append(ends[i]+one_day)
        ends[i]+=one_day
    
secondlast_thirtymins_df = pd.DataFrame(columns=['bidder_id','time'])

for i in range(9):
    day = days[i]
    day = day.drop(columns=['auction'],axis=1)
    thirtymins = day.loc[(day.time > end_times[i]-(thirty_mins*2)) & (day.time <= (end_times[i]-thirty_mins))]
    secondlast_thirtymins_df = pd.concat([secondlast_thirtymins_df,thirtymins],ignore_index=True)
    #print(f'Day {i+1} done.') # to track output
    
secondlast_thirtymins_df = secondlast_thirtymins_df.groupby('bidder_id').count().rename({'time':'bids_in_secondlastthirty'},axis=1)

#### `meanbids_in_20mins_df`
- mean number of bids placed in each 20min interval

In [59]:
one_min = 3157885304.6594987
twenty_df = bids_df[['bidder_id','time']]

start = 9631916842105263 #inclusive
end = start+(20*one_min)

meanbids_in_20mins_df = pd.DataFrame(columns=['bidder_id','time'])

for i in range(2232):
    
    bids = twenty_df.loc[(twenty_df.time >= start) & (twenty_df.time < end)]
    count = bids.groupby('bidder_id').count().reset_index()
    meanbids_in_20mins_df = pd.concat([meanbids_in_20mins_df,count],ignore_index=True)
    
    # update start and end time
    start += (20*one_min)
    end += (20*one_min)
    
    # print(i,end=' ') # track output

meanbids_in_20mins_df['time'] = meanbids_in_20mins_df['time'].apply(int)
meanbids_in_20mins_df = meanbids_in_20mins_df.groupby('bidder_id').mean().rename({'time':'avg_bids_in_20mins'},axis=1)

### bidding_activity_df

In [61]:
bidding_activity_df = pd.concat([first_thirtymins_df, second_thirtymins_df, last_thirtymins_df, 
                                 secondlast_thirtymins_df, mean_time_variance_per_day_df, meanbids_in_20mins_df],axis=1)
bidding_activity_df

,bids_in_firstthirty,bids_in_secondthirty,bids_in_lastthirty,bids_in_secondlastthirty,mean_time_variance_per_day,avg_bids_in_20mins
0013f9b8d1f462df4462e1c1216e441ba6e18,1.0,1.0,NaN,1.0,1.469263e+24,1.000000
00402f50c4086f320cb6bf94f04462ea32441,9.0,20.0,5.0,3.0,2.152910e+24,1.930233
0040cea6b93afd86768c365d89513ffb7c0ba,1.0,NaN,3.0,1.0,2.909119e+24,1.148148
00512db4ae953baed983a4bcfa335e7412013,44.0,34.0,25.0,24.0,1.978105e+24,3.348718
006dae761f00a5fab2736055b9bd33c8ef8a3,26.0,12.0,24.0,13.0,1.996014e+24,3.153846
...,...,...,...,...,...,...
ff5a96d8ab4600bd1abf92c7ef4303a96b426,NaN,NaN,NaN,NaN,NaN,1.000000
ff86fb9518e542475e832ee6d299b3bed630b,NaN,NaN,NaN,NaN,NaN,1.000000
ff9773a58425024f0933ef21ad665f79d9705,NaN,NaN,NaN,NaN,5.159408e+23,1.142857
ffc8582643deb57f3f390d36c77c10f9810c0,NaN,NaN,NaN,NaN,8.277338e+23,1.000000
ffe66dcb4b34bdbb5e17d7db7b1395e3fbbb7,NaN,NaN,NaN,NaN,2.395598e+21,1.500000

---

## Bidder Downtime
- Bidding downtime would be the time between a bidder's nth bid and the same bidder's (n+1)th bid

First we extract the time between the bids for each transaction by a bidder

In [68]:
# shortcut to get bidder_downtime_raw_df
bidder_downtime_raw_df = pd.read_csv('raw_data/bidder_downtime_raw.csv')

In [7]:
days = [day1,day2,day3,day4,day5,day6,day7,day8,day9]

bidder_downtime_raw_df = pd.DataFrame(columns=['bidder_id','time'])

for day in days:
    
    day = day.drop(columns='auction',axis=1)
    unique_bidders = list(day.bidder_id.unique())
    
    for bidder in unique_bidders:
        bidder_df = day.loc[day.bidder_id == bidder].set_index('bidder_id')
        bidder_df = bidder_df.diff()
        bidder_df = bidder_df.reset_index()
        bidder_downtime_raw_df = pd.concat([bidder_downtime_raw_df,bidder_df],ignore_index=True)
        
    # print('-1 Day Done-') # to track output

#### `mean_downtime_df`

In [69]:
mean_downtime_df = bidder_downtime_raw_df.groupby('bidder_id').mean().rename({'time':'mean_bidder_downtime'},axis=1)

#### `median_downtime_df`

In [70]:
median_downtime_df = bidder_downtime_raw_df.groupby('bidder_id').median().rename({'time':'median_bidder_downtime'},axis=1)

#### `var_downtime_df`

In [71]:
var_downtime_df = bidder_downtime_raw_df.groupby('bidder_id').var().rename({'time':'var_bidder_downtime'},axis=1)

### bidder_downtime_df

In [72]:
bidder_downtime_df = pd.concat([mean_downtime_df,median_downtime_df,var_downtime_df],axis=1)
bidder_downtime_df

,mean_bidder_downtime,median_bidder_downtime,var_bidder_downtime
bidder_id,,,
0013f9b8d1f462df4462e1c1216e441ba6e18,1.158137e+12,1.147842e+12,1.177492e+24
0014e3b911d1420e43ced1dc4fc18fde0fd0c,1.534697e+12,1.673368e+12,3.739317e+23
002828f800c5132e297cfe3d44fbde9aeac51,NaN,NaN,NaN
00402f50c4086f320cb6bf94f04462ea32441,5.433119e+10,2.350000e+10,5.378771e+21
0040cea6b93afd86768c365d89513ffb7c0ba,8.105411e+11,4.161053e+11,1.034761e+24
...,...,...,...
ffd49be672b1ba493b07dccf29311045c5392,8.135726e+10,4.310526e+10,1.174233e+22
ffdd8ed91a683b0f2a8237798ebe9214e3c43,1.161579e+12,6.194737e+10,3.811854e+24
ffde8717e9a547d536a4e9c3f44782829c021,8.269094e+11,5.996316e+11,7.614567e+23
ffe66dcb4b34bdbb5e17d7db7b1395e3fbbb7,4.502632e+10,4.502632e+10,2.209375e+21
ffef2a34068ab5328795bc9ed2da46aa29626,6.668525e+10,2.589474e+10,1.474745e+22

---

## Others

#### `mean_time_between_diff_ips`

In [80]:
# shortcut to get time_between_diff_ips_raw_df
time_between_diff_ips_raw_df = pd.read_csv('raw_data/time_between_diff_ips_raw.csv')

In [16]:
ip_mean_time_df = bids_df.groupby(['bidder_id','ip','time']).count().reset_index().drop(columns=['ip','auction','merchandise','device','country','url'],axis=1)

unique_bidders = list(ip_mean_time_df.bidder_id.unique())

time_between_diff_ips_raw_df = pd.DataFrame(columns=['bidder_id','time'])

count = 0 # for tracking output
for bidder in unique_bidders:
    count += 1
    bidder_df = ip_mean_time_df.loc[ip_mean_time_df.bidder_id == bidder]
    bidder_df = bidder_df.sort_values('time').set_index('bidder_id').diff().reset_index()
    time_between_diff_ips_raw_df = pd.concat([time_between_diff_ips_raw_df, bidder_df],ignore_index=True)
    # print (count, end=' ') # to track output
    
time_between_diff_ips_raw_df = time_between_diff_ips_raw_df.rename({'time':'time_between_diff_ips'},axis=1)

In [81]:
time_between_diff_ips_raw_df = time_between_diff_ips_raw_df.rename({'time_between_diff_ips':'mean_time_between_diff_ips'},axis=1)
mean_time_between_diff_ips_df = time_between_diff_ips_raw_df.groupby('bidder_id').mean()
mean_time_between_diff_ips_df

                                       mean_time_between_diff_ips
bidder_id
0013f9b8d1f462df4462e1c1216e441ba6e18                9.680602e+11
0014e3b911d1420e43ced1dc4fc18fde0fd0c                2.120026e+12
002828f800c5132e297cfe3d44fbde9aeac51                6.236816e+13
00402f50c4086f320cb6bf94f04462ea32441                5.466914e+10
0040cea6b93afd86768c365d89513ffb7c0ba                2.548244e+12
...                                                           ...
ffd49be672b1ba493b07dccf29311045c5392                8.130728e+10
ffdd8ed91a683b0f2a8237798ebe9214e3c43                1.467118e+13
ffde8717e9a547d536a4e9c3f44782829c021                3.301009e+12
ffe66dcb4b34bdbb5e17d7db7b1395e3fbbb7                4.502632e+10
ffef2a34068ab5328795bc9ed2da46aa29626                6.668834e+10

[6614 rows x 1 columns]

---

## Old and unclassified features

### bids_per_url_df

In [82]:
bids_per_url_df = bids_df.groupby(['bidder_id','url']).count().reset_index().drop(columns=['merchandise','device','time','country','ip'])
bids_per_url_df = bids_per_url_df.rename({'auction':'bids_per_url'},axis=1)
bids_per_url_df = bids_per_url_df.groupby('bidder_id').aggregate([min, max,'mean','median','count']).bids_per_url
bids_per_url_df = bids_per_url_df.rename(columns={'min': 'min_bids_per_url',
                                                  'max': 'max_bids_per_url',
                                                  'mean': 'mean_bids_per_url',
                                                  'median': 'median_bids_per_url',
                                                  'count': 'num_of_url_used'})
bids_per_url_df

,min_bids_per_url,max_bids_per_url,mean_bids_per_url,median_bids_per_url,num_of_url_used
bidder_id,,,,,
0013f9b8d1f462df4462e1c1216e441ba6e18,1,4,2.000000,1.5,4
0014e3b911d1420e43ced1dc4fc18fde0fd0c,1,3,1.750000,1.5,4
002828f800c5132e297cfe3d44fbde9aeac51,2,2,2.000000,2.0,1
00402f50c4086f320cb6bf94f04462ea32441,1,67,2.540816,1.0,98
0040cea6b93afd86768c365d89513ffb7c0ba,1,19,7.750000,5.5,4
...,...,...,...,...,...
ffd49be672b1ba493b07dccf29311045c5392,1,32,4.200000,1.0,40
ffdd8ed91a683b0f2a8237798ebe9214e3c43,1,4,2.500000,2.5,2
ffde8717e9a547d536a4e9c3f44782829c021,1,19,6.000000,2.0,4
ffe66dcb4b34bdbb5e17d7db7b1395e3fbbb7,1,2,1.500000,1.5,2
ffef2a34068ab5328795bc9ed2da46aa29626,1,24,3.121212,1.0,33

### bids_per_ip_df

In [83]:
bids_per_ip_df = bids_df.groupby(['bidder_id','ip']).count().reset_index().drop(columns=['merchandise','device','time','country','url'])
bids_per_ip_df = bids_per_ip_df.rename({'auction':'bids_per_ip'},axis=1)
bids_per_ip_df = bids_per_ip_df.groupby('bidder_id').aggregate([min, max,'mean','median','count']).bids_per_ip
bids_per_ip_df = bids_per_ip_df.rename(columns={'min': 'min_bids_per_ip',
                                                'max': 'max_bids_per_ip',
                                                'mean': 'mean_bids_per_ip',
                                                'median': 'median_bids_per_ip',
                                                'count': 'num_of_ip_used'})
bids_per_ip_df

,min_bids_per_ip,max_bids_per_ip,mean_bids_per_ip,median_bids_per_ip,num_of_ip_used
bidder_id,,,,,
0013f9b8d1f462df4462e1c1216e441ba6e18,1,1,1.000000,1.0,8
0014e3b911d1420e43ced1dc4fc18fde0fd0c,1,1,1.000000,1.0,7
002828f800c5132e297cfe3d44fbde9aeac51,1,1,1.000000,1.0,2
00402f50c4086f320cb6bf94f04462ea32441,1,11,1.649007,1.0,151
0040cea6b93afd86768c365d89513ffb7c0ba,1,4,1.107143,1.0,28
...,...,...,...,...,...
ffd49be672b1ba493b07dccf29311045c5392,1,12,1.647059,1.0,102
ffdd8ed91a683b0f2a8237798ebe9214e3c43,1,2,1.250000,1.0,4
ffde8717e9a547d536a4e9c3f44782829c021,1,1,1.000000,1.0,24
ffe66dcb4b34bdbb5e17d7db7b1395e3fbbb7,1,1,1.000000,1.0,3
ffef2a34068ab5328795bc9ed2da46aa29626,1,4,1.410959,1.0,73

### sets_df

In [84]:
bids_df['bin'] = pd.cut(bids_df['time'], 
                        bins=[0,9660000000000000,9730000000000000,9773000000000000], 
                        labels=["set1", "set2", "set3"])

set1_bids_df = bids_df.loc[bids_df.bin == 'set1'] # transaction in set 1
set2_bids_df = bids_df.loc[bids_df.bin == 'set2'] # transaction in set 2
set3_bids_df = bids_df.loc[bids_df.bin == 'set3'] # transaction in set 3

set1_df = set1_bids_df.groupby('bidder_id').count()
set1_df = set1_df.drop(columns=['device','time','country','ip','url','merchandise','bin']).rename({'auction':'bids_in_set1'},axis=1)

set2_df = set2_bids_df.groupby('bidder_id').count()
set2_df = set2_df.drop(columns=['device','time','country','ip','url','merchandise','bin']).rename({'auction':'bids_in_set2'},axis=1)

set3_df = set3_bids_df.groupby('bidder_id').count()
set3_df = set3_df.drop(columns=['device','time','country','ip','url','merchandise','bin']).rename({'auction':'bids_in_set3'},axis=1)

sets_df = pd.concat([set1_df,set2_df,set3_df],axis=1)

if 'bin' in bids_df.columns:
    bids_df = bids_df.drop(columns=['bin'])
    
sets_df

,bids_in_set1,bids_in_set2,bids_in_set3
002828f800c5132e297cfe3d44fbde9aeac51,1.0,1.0,NaN
0040cea6b93afd86768c365d89513ffb7c0ba,12.0,19.0,NaN
00512db4ae953baed983a4bcfa335e7412013,724.0,582.0,NaN
00a1a97c89123d4a799cb3a3dc4495a022f11,1.0,3.0,NaN
00ba8995ec525897b7610cbd4cc7d6a6269df,2.0,1.0,NaN
...,...,...,...
ffb922bfbecb47ce63472acb21444ff6f1a4c,NaN,NaN,3.0
ffc6f0c2b63923d5883dd1f7ebd19cfcfedd2,NaN,NaN,10.0
ffcf256495c1334dda186fe094fdc4829ddde,NaN,NaN,43255.0
ffd49be672b1ba493b07dccf29311045c5392,NaN,NaN,168.0
ffe66dcb4b34bdbb5e17d7db7b1395e3fbbb7,NaN,NaN,3.0

### bids_per_country_df

In [85]:
bids_per_country_df = bids_df[['bidder_id','country','ip']].groupby(['bidder_id','country']).count().groupby('bidder_id').mean().rename({'ip':'mean_bid_per_country'},axis=1)
bids_per_country_df

                                       mean_bid_per_country
bidder_id
0013f9b8d1f462df4462e1c1216e441ba6e18              4.000000
0014e3b911d1420e43ced1dc4fc18fde0fd0c              1.750000
002828f800c5132e297cfe3d44fbde9aeac51              2.000000
00402f50c4086f320cb6bf94f04462ea32441             11.857143
0040cea6b93afd86768c365d89513ffb7c0ba              5.166667
...                                                     ...
ffd49be672b1ba493b07dccf29311045c5392             33.600000
ffdd8ed91a683b0f2a8237798ebe9214e3c43              5.000000
ffde8717e9a547d536a4e9c3f44782829c021              4.000000
ffe66dcb4b34bdbb5e17d7db7b1395e3fbbb7              1.500000
ffef2a34068ab5328795bc9ed2da46aa29626              7.923077

[6609 rows x 1 columns]

### objects_df

In [86]:
objects_df = bids_df.groupby('bidder_id').nunique() 
objects_df = objects_df.loc[:,['device','country','auction']]
objects_df = objects_df.rename({'device':'unique_devices_used',
                                'country':'unique_countries_used',
                                'auction':'num_of_unique_auctions'},axis=1)
objects_df

,unique_devices_used,unique_countries_used,num_of_unique_auctions
bidder_id,,,
0013f9b8d1f462df4462e1c1216e441ba6e18,7,2,6
0014e3b911d1420e43ced1dc4fc18fde0fd0c,7,4,7
002828f800c5132e297cfe3d44fbde9aeac51,1,1,2
00402f50c4086f320cb6bf94f04462ea32441,99,21,89
0040cea6b93afd86768c365d89513ffb7c0ba,21,6,23
...,...,...,...
ffd49be672b1ba493b07dccf29311045c5392,69,5,20
ffdd8ed91a683b0f2a8237798ebe9214e3c43,3,1,4
ffde8717e9a547d536a4e9c3f44782829c021,20,6,16
ffe66dcb4b34bdbb5e17d7db7b1395e3fbbb7,2,2,3
ffef2a34068ab5328795bc9ed2da46aa29626,50,13,70

---

## Inspiried by fakeplastictress
- [ ] The proportion of each bidder’s bids that were in each day ( I believe there were 9 days of bid data).
- [ ] The proportion of each bidder’s bids that were in each of 8 3-hour time slots.
- [ ] The mean time of day for the bids of each bidder.
- [ ] The frequency of each final part of the IP address averaged for each bidder – the first three parts had no positive effect.
- [ ] The average proportion of bots associated with each device code. NB – (difficult to put into CV without data leakage – a slightly different data set for each fold!)
- [ ] Same as above for each country code.
- [X] The total number of bids made in each auction averaged for each bidder. (i.e. did the bidder tend to bid in popular auctions or less popular ones)
- [ ] The maximum number of auctions a bidder has participated in, in one hour.

### auction_bid_count_df
- This is indicative of whether the bidder tend to participate in more popular or less popular auctions

In [27]:
# find total number of bid in each auction
auction_bid_count_df = bids_df.groupby('auction').count()
auction_bid_count_df = auction_bid_count_df[['ip']].rename({'ip':'mean_auction_bid_count_per_bidder'},axis=1).reset_index()

# get unique auctions for unique bidders
unique_auctions_per_bidder = bids_df.groupby(['bidder_id','auction']).count().reset_index()
unique_auctions_per_bidder = unique_auctions_per_bidder[['bidder_id','auction']]

# merge the two df above
auction_bid_count_per_bidder_df = unique_auctions_per_bidder.merge(auction_bid_count_df,how='left',on='auction')
auction_bid_count_per_bidder_df = auction_bid_count_per_bidder_df.drop(columns='auction',axis=1)
mean_auction_bid_count_per_bidder_df = auction_bid_count_per_bidder_df.groupby('bidder_id').mean()

mean_auction_bid_count_per_bidder_df

                                       mean_auction_bid_count_per_bidder
bidder_id
0013f9b8d1f462df4462e1c1216e441ba6e18                        7085.833333
0014e3b911d1420e43ced1dc4fc18fde0fd0c                        7406.571429
002828f800c5132e297cfe3d44fbde9aeac51                       22322.500000
00402f50c4086f320cb6bf94f04462ea32441                        4154.842697
0040cea6b93afd86768c365d89513ffb7c0ba                        1551.695652
...                                                                  ...
ffd49be672b1ba493b07dccf29311045c5392                        2822.400000
ffdd8ed91a683b0f2a8237798ebe9214e3c43                        1130.750000
ffde8717e9a547d536a4e9c3f44782829c021                       46390.125000
ffe66dcb4b34bdbb5e17d7db7b1395e3fbbb7                        1457.666667
ffef2a34068ab5328795bc9ed2da46aa29626                        7404.000000

[6614 rows x 1 columns]

---

## Combining all features!

In [31]:
# combining features in both train_df and test_df
train_df = pd.read_csv('data/train.csv')
train_df = train_df.set_index('bidder_id')

test_df = pd.read_csv('data/test.csv')
test_df = test_df.set_index('bidder_id')

train_test_combined_df = pd.concat([train_df,test_df])
# train_test_combined

In [87]:
bids_df_combined = pd.concat([train_test_combined_df,
                              reaction_time_df,
                              bids_counts_df,
                              bidding_activity_df,
                              bidder_downtime_df,
                              mean_time_between_diff_ips_df,
                              bids_per_url_df,
                              bids_per_ip_df,
                              sets_df,
                              bids_per_country_df,
                              objects_df,
                              mean_auction_bid_count_per_bidder_df
                             ],axis=1)
bids_df_combined = bids_df_combined.reset_index()
bids_df_combined = bids_df_combined.rename(columns={'index':'bidder_id'})
bids_df_combined

,bidder_id,payment_account,address,outcome,mean_reaction_time,median_reaction_time,var_reaction_time,mean_bids_per_auction,median_bids_per_auction,mean_bids_per_day,total_bids,bids_in_firstthirty,bids_in_secondthirty,bids_in_lastthirty,bids_in_secondlastthirty,mean_time_variance_per_day,avg_bids_in_20mins,mean_bidder_downtime,median_bidder_downtime,var_bidder_downtime,mean_time_between_diff_ips,min_bids_per_url,max_bids_per_url,mean_bids_per_url,median_bids_per_url,num_of_url_used,min_bids_per_ip,max_bids_per_ip,mean_bids_per_ip,median_bids_per_ip,num_of_ip_used,bids_in_set1,bids_in_set2,bids_in_set3,mean_bid_per_country,unique_devices_used,unique_countries_used,num_of_unique_auctions,mean_auction_bid_count_per_bidder
0,3758013f9a2c4f9d8670e709d9e8beaba6f57,32a6f444ff094840b58be6bb6db6a04fe4f85,4f2ed7fc454d535ecba88bc7f854925dfe4ab,0.0,6.537626e+10,1.826316e+10,3.219385e+22,1.612903,1.0,16.666667,50.0,NaN,2.0,NaN,1.0,1.880589e+24,1.315789,2.403942e+11,1.294737e+11,1.126657e+23,2.708851e+11,1.0,22.0,3.333333,1.0,15.0,1.0,4.0,1.351351,1.0,37.0,NaN,NaN,50.0,6.250000,30.0,8.0,25.0,3826.160000
1,8a12c97c9dac9ef7fcbbceaf7522447cf6e49,eb0ae407d20ab19351c5271abe4ca12ce84c0,1c73853ef410e4095382f8d6ddeb0b9d22bb0,0.0,5.263158e+07,5.263158e+07,NaN,1.000000,1.0,1.000000,1.0,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,1.0,1.0,1.000000,1.0,1.0,1.0,1.0,1.000000,1.0,1.0,NaN,1.0,NaN,1.000000,1.0,1.0,1.0,537347.000000
2,27b3a0fecc63bf830bc44961c90f330308364,87dbae72fd15fa13f14217e47f32fa0ea9417,c4bbeba55def4b3861ac24cc5efd82b886b9b,0.0,3.508772e+08,5.263158e+07,2.668513e+17,1.500000,1.5,3.000000,3.0,NaN,NaN,NaN,NaN,1.317666e+22,1.000000,1.147895e+11,1.147895e+11,1.994460e+17,1.147895e+11,1.0,2.0,1.500000,1.5,2.0,1.0,1.0,1.000000,1.0,3.0,NaN,NaN,3.0,1.000000,1.0,3.0,2.0,105236.000000
3,2a2b18bbdfa736637911cf407799b409112a2,40a0df1d610ef30a8f01d48198ab60bee51e2,021918f1b3fc828970b230eaf4d49f8a93b95,0.0,1.498188e+10,4.578947e+09,6.095710e+20,1.452381,1.0,20.333333,61.0,1.0,3.0,1.0,2.0,2.282119e+24,1.418605,2.192976e+11,1.145263e+11,1.037535e+23,2.234737e+11,1.0,41.0,6.777778,1.0,9.0,1.0,5.0,1.794118,1.5,34.0,NaN,NaN,61.0,15.250000,22.0,4.0,33.0,7180.757576
4,3fdc7c645e5e131c05f1ae112dbae407523c5,3d20d9941901359e5fed3dfc0c5bf45dfd968,d6331a777cabb7c5df46c6a0377136b904614,0.0,1.151001e+10,1.000000e+09,1.154326e+22,4.320217,2.0,530.666667,3184.0,172.0,182.0,87.0,74.0,2.257939e+24,7.421911,8.559687e+09,4.842105e+09,1.157873e+20,2.427804e+10,1.0,591.0,16.757895,2.0,190.0,1.0,44.0,1.373598,1.0,2318.0,1608.0,1576.0,NaN,44.222222,462.0,72.0,377.0,3117.514589
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6708,ffd49be672b1ba493b07dccf29311045c5392,67fb4e3228b17f50d9fd3b55bcfa0baa102ce,2ef4838010247596bb0ffa2fcd9d37fa1a86c,NaN,1.574299e+11,8.078947e+10,3.878959e+22,5.600000,2.5,56.000000,168.0,3.0,7.0,6.0,5.0,2.296792e+24,1.663366,8.135726e+10,4.310526e+10,1.174233e+22,8.130728e+10,1.0,32.0,4.200000,1.0,40.0,1.0,12.0,1.647059,1.0,102.0,NaN,NaN,168.0,33.600000,69.0,5.0,20.0,2822.400000
6709,ffdd8ed91a683b0f2a8237798ebe9214e3c43,92feaccddb5d01938a88a48805f1c289b9751,bf62df480501dc376cb31137fc63526266dbe,NaN,1.106632e+11,9.473684e+10,1.204035e+22,1.000000,1.0,2.500000,5.0,NaN,NaN,NaN,1.0,2.917624e+24,1.250000,1.161579e+12,6.194737e+10,3.811854e+24,1.467118e+13,1.0,4.0,2.500000,2.5,2.0,1.0,2.0,1.250000,1.0,4.0,2.0,3.0,NaN,5.000000,3.0,1.0,4.0,1130.750000
6710,ffde8717e9a547d536a4e9c3f44782829c021,7d8f1523053775511a45f6231eb4da804da42,c3b54d8d6e95419603fad9e019e9d5f2fb203,NaN,1.230263e+09,3.947368e+08,2.836279e+18,1.142857,1.0,4.000000,24.0,NaN,NaN,1.0,1.0,1.842225e+24,1.090909,8.269094e+11,5.996316e+11,7.614567e+23,3.301009e+12,1.0,19.0,6.000000,2.0,4.0,1.0,1.0,1.000000,1.0,24.0,16.0,8.0,NaN,4.000000,20.0,6.0,16.0,46390.125000
6711,ffe66dcb4b34bdbb5e17d7db7b1395e3fbbb7,8d7b640b6421cbbbe5c3cb7e1e83ff3278d41,cb5d49cf7d2efcc7a958278b219823b890920,NaN,1.019298e+10,1.026316e+10,3.989289e+19,1.000000,1.0,3.000000,3.0,NaN,NaN,NaN,NaN,2.395598e+21,1.500000,4.502632e+10,4.502632e+10,2.209375e+21,4.502632e+10,1.0,2.0,1.500000,1.5,2.0,1.0,1.0,1.000000,1.0,3.0,NaN,NaN,3.0,1.500000,2.0,2.0,3.0,1457.666667
6712,ffef2a34068ab5328795bc9ed2da46aa29626,0025b4892929407f73b5c2b34678b8276d188,b609d37bf90ed24324ec8378444a1c4c6c894,NaN,4.677057e+09,1.157895e+09,1.454074e+20,1.337662,1.0,51.500000,103.0,15.0,5.0,2.0,3.0,1.502669e+24,1.943396,6.668525e+10,2.589474e+10,1.474745e+22,6.668834e+10,1.0,24.0,3.121212,1.0,33.0,1.0,4.0,1.410959,1.0,73.0,NaN,103.0,NaN,7.923077,50.0,13.0,70.0,7404.000000

### Fill in missing values

In [89]:
bids_df_combined.isnull().sum()

bidder_id                               0
payment_account                         0
address                                 0
outcome                              4700
mean_reaction_time                    110
median_reaction_time                  110
var_reaction_time                    1168
mean_bids_per_auction                  99
median_bids_per_auction                99
mean_bids_per_day                      99
total_bids                             99
bids_in_firstthirty                  3434
bids_in_secondthirty                 3472
bids_in_lastthirty                   3892
bids_in_secondlastthirty             3851
mean_time_variance_per_day           1543
avg_bids_in_20mins                     99
mean_bidder_downtime                 1543
median_bidder_downtime               1543
var_bidder_downtime                  2072
mean_time_between_diff_ips           1157
min_bids_per_url                       99
max_bids_per_url                       99
mean_bids_per_url                      99
median_bids_per_url                    99
num_of_url_used                        99
min_bids_per_ip                        99
max_bids_per_ip                        99
mean_bids_per_ip                       99
median_bids_per_ip                     99
num_of_ip_used                         99
bids_in_set1                         3697
bids_in_set2                         3699
bids_in_set3                         3759
mean_bid_per_country                  104
unique_devices_used                    99
unique_countries_used                  99
num_of_unique_auctions                 99
mean_auction_bid_count_per_bidder      99
dtype: int64

In [91]:
# Feature Set 1: Reaction Time
bids_df_combined['mean_reaction_time'].fillna(bids_df_combined['mean_reaction_time'].median(), inplace = True)
bids_df_combined['median_reaction_time'].fillna(bids_df_combined['median_reaction_time'].median(), inplace = True)
bids_df_combined['var_reaction_time'].fillna(bids_df_combined['var_reaction_time'].median(), inplace = True)

# Feature Set 2: Bids Counts
bids_df_combined['mean_bids_per_auction'].fillna(bids_df_combined['mean_bids_per_auction'].median(), inplace = True)
bids_df_combined['median_bids_per_auction'].fillna(bids_df_combined['median_bids_per_auction'].median(), inplace = True)
bids_df_combined['mean_bids_per_day'].fillna(bids_df_combined['mean_bids_per_day'].median(), inplace = True)
bids_df_combined['total_bids'].fillna(bids_df_combined['total_bids'].median(), inplace = True)

# Feature Set 3: Bidding Activity
bids_df_combined['bids_in_firstthirty'] = bids_df_combined['bids_in_firstthirty'].fillna(0)
bids_df_combined['bids_in_secondthirty'] = bids_df_combined['bids_in_secondthirty'].fillna(0)
bids_df_combined['bids_in_secondlastthirty'] = bids_df_combined['bids_in_secondlastthirty'].fillna(0)
bids_df_combined['bids_in_lastthirty'] = bids_df_combined['bids_in_lastthirty'].fillna(0)
bids_df_combined['mean_time_variance_per_day'].fillna(bids_df_combined['mean_time_variance_per_day'].median(), inplace = True)
bids_df_combined['avg_bids_in_20mins'] = bids_df_combined['avg_bids_in_20mins'].fillna(0)

# Feature Set 4: Bidder Downtime
bids_df_combined['mean_bidder_downtime'].fillna(bids_df_combined['mean_bidder_downtime'].median(), inplace = True)
bids_df_combined['median_bidder_downtime'].fillna(bids_df_combined['median_bidder_downtime'].median(), inplace = True)
bids_df_combined['var_bidder_downtime'].fillna(bids_df_combined['var_bidder_downtime'].median(), inplace = True)

# Feature Set 5: Others
bids_df_combined['mean_time_between_diff_ips'].fillna(bids_df_combined['mean_time_between_diff_ips'].median(), inplace = True)

# Feature Set 6: Old and unclassified
bids_df_combined['min_bids_per_url'].fillna(bids_df_combined['min_bids_per_url'].median(), inplace = True)
bids_df_combined['max_bids_per_url'].fillna(bids_df_combined['max_bids_per_url'].median(), inplace = True)
bids_df_combined['mean_bids_per_url'].fillna(bids_df_combined['mean_bids_per_url'].median(), inplace = True)
bids_df_combined['median_bids_per_url'].fillna(bids_df_combined['median_bids_per_url'].median(), inplace = True)
bids_df_combined['num_of_url_used'].fillna(bids_df_combined['num_of_url_used'].median(), inplace = True)

bids_df_combined['min_bids_per_ip'].fillna(bids_df_combined['min_bids_per_ip'].median(), inplace = True)
bids_df_combined['max_bids_per_ip'].fillna(bids_df_combined['max_bids_per_ip'].median(), inplace = True)
bids_df_combined['mean_bids_per_ip'].fillna(bids_df_combined['mean_bids_per_ip'].median(), inplace = True)
bids_df_combined['median_bids_per_ip'].fillna(bids_df_combined['median_bids_per_ip'].median(), inplace = True)
bids_df_combined['num_of_ip_used'].fillna(bids_df_combined['num_of_ip_used'].median(), inplace = True)

bids_df_combined['bids_in_set1'] = bids_df_combined['bids_in_set1'].fillna(0)
bids_df_combined['bids_in_set2'] = bids_df_combined['bids_in_set2'].fillna(0)
bids_df_combined['bids_in_set3'] = bids_df_combined['bids_in_set3'].fillna(0)

bids_df_combined['unique_devices_used'].fillna(bids_df_combined['unique_devices_used'].median(), inplace = True)
bids_df_combined['unique_countries_used'].fillna(bids_df_combined['unique_countries_used'].median(), inplace = True)

bids_df_combined['mean_bid_per_country'].fillna(bids_df_combined['mean_bid_per_country'].median(), inplace = True)

bids_df_combined['num_of_unique_auctions'].fillna(bids_df_combined['num_of_unique_auctions'].median(), inplace = True)

# Feature set 7: Inspired by fakeplastictrees
bids_df_combined['mean_auction_bid_count_per_bidder'].fillna(bids_df_combined['mean_auction_bid_count_per_bidder'].median(), inplace = True)

# `outcome` column
bids_df_combined['outcome'] = bids_df_combined['outcome'].fillna('Unknown')

### Add on features

In [92]:
# fractions
bids_df_combined['firstthirty_fraction'] = bids_df_combined.bids_in_firstthirty / bids_df_combined.total_bids
bids_df_combined['secondthirty_fraction'] = bids_df_combined.bids_in_secondthirty / bids_df_combined.total_bids
bids_df_combined['lastthirty_fraction'] = bids_df_combined.bids_in_lastthirty / bids_df_combined.total_bids
bids_df_combined['secondlastthirty_fraction'] = bids_df_combined.bids_in_secondlastthirty / bids_df_combined.total_bids

In [93]:
bids_df_combined.isnull().sum()

bidder_id                            0
payment_account                      0
address                              0
outcome                              0
mean_reaction_time                   0
median_reaction_time                 0
var_reaction_time                    0
mean_bids_per_auction                0
median_bids_per_auction              0
mean_bids_per_day                    0
total_bids                           0
bids_in_firstthirty                  0
bids_in_secondthirty                 0
bids_in_lastthirty                   0
bids_in_secondlastthirty             0
mean_time_variance_per_day           0
avg_bids_in_20mins                   0
mean_bidder_downtime                 0
median_bidder_downtime               0
var_bidder_downtime                  0
mean_time_between_diff_ips           0
min_bids_per_url                     0
max_bids_per_url                     0
mean_bids_per_url                    0
median_bids_per_url                  0
num_of_url_used                      0
min_bids_per_ip                      0
max_bids_per_ip                      0
mean_bids_per_ip                     0
median_bids_per_ip                   0
num_of_ip_used                       0
bids_in_set1                         0
bids_in_set2                         0
bids_in_set3                         0
mean_bid_per_country                 0
unique_devices_used                  0
unique_countries_used                0
num_of_unique_auctions               0
mean_auction_bid_count_per_bidder    0
firstthirty_fraction                 0
secondthirty_fraction                0
lastthirty_fraction                  0
secondlastthirty_fraction            0
dtype: int64

### Save to CSV file

In [205]:
bids_df_combined.to_csv('FINALcombined.csv',index=False)

-------------------------------------------------------------------------- End of Feature Engineering --------------------------------------------------------------------------